import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import NextTopLoader from "nextjs-toploader";
import ScrollBtn from "@/components/buttons/ScrollBtn";
import Header from "./components/server_components/Header";
import SideBar from "./components/server_components/SideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="x-ua-compatible" content="ie=edge" />
        <title>Olle - Admin</title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link
          rel="shortcut icon"
          type="image/x-icon"
          href="../assets/admin_assets/img/favicon.png"
        />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;300;400;500;600;700;800&family=Poppins:wght@300;400;500;600;700;800;900&family=Roboto:wght@400;500;700;900&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://cdn.materialdesignicons.com/4.4.95/css/materialdesignicons.min.css"
          rel="stylesheet"
        />
        <link
          href="../assets/admin_assets/plugins/daterangepicker/daterangepicker.css"
          rel="stylesheet"
        />
        <link
          href="../assets/admin_assets/plugins/simplebar/simplebar.css"
          rel="stylesheet"
        />
        <link
          id="ekka-css"
          href="../assets/admin_assets/css/ekka.css"
          rel="stylesheet"
        />

        <link href="../assets/admin_assets/img/favicon.png" rel="shortcut icon" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ScrollBtn></ScrollBtn>
        <main className="min-h-screen flex flex-col">
  <NextTopLoader
    color="#FFFFFF"
    initialPosition={0.08}
    crawlSpeed={200}
    height={3}
    crawl={true}
    showSpinner={false}
  />
  {/* Header stays on top */}
  <Header />

  {/* Content and Sidebar next to each other */}
  <div className="d-flex" style={{ marginTop: "50px", maxHeight: "calc(100vh - 75px)"}}>
    {/* Sidebar on the left */}
    <div style={{overflowY: "auto", overflowX: "hidden", width: "250px"}}>
      <SideBar />
    </div>

    {/* Main content takes the remaining space */}
    <div style={{backgroundColor: "rgb(138 144 157 / 5%)", maxHeight: "calc(100vh - 50px)", overflowY: "auto"}} className="w-100">
      <div style={{minHeight: "100vh"}}>
        {children}
      </div>
    </div>
  </div>
</main>
        <script src="../assets/admin_assets/plugins/jquery/jquery-3.5.1.min.js"></script>
	<script src="../assets/admin_assets/js/bootstrap.bundle.min.js"></script>
	<script src="../assets/admin_assets/plugins/simplebar/simplebar.min.js"></script>
	<script src="../assets/admin_assets/plugins/jquery-zoom/jquery.zoom.min.js"></script>
	<script src="../assets/admin_assets/plugins/slick/slick.min.js"></script>
	<script src="../assets/admin_assets/plugins/charts/Chart.min.js"></script>
	<script src="../assets/admin_assets/js/chart.js"></script>
	<script src="../assets/admin_assets/plugins/charts/google-map-loader.js"></script>
	<script src="../assets/admin_assets/plugins/charts/google-map.js"></script>
	<script src="../assets/admin_assets/plugins/daterangepicker/moment.min.js"></script>
    <script src="../assets/admin_assets/plugins/daterangepicker/daterangepicker.js"></script>
	<script src="../assets/admin_assets/js/date-range.js"></script>
	<script src="../assets/admin_assets/plugins/options-sidebar/optionswitcher.js"></script>
	<script src="../assets/admin_assets/js/ekka.js"></script>
      </body>
    </html>
  );
}
